name: Deploy CDK

on:
  push:
    branches:
      - main
jobs:
  deploy:
    environment: cdk_keys
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "Checking out code"
      - name: Check variables
        run: echo "Checking variables"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Check list lambda functions
        run: aws lambda list-functions